### PR TITLE
Added a service worker to enable basic PWA functionality

### PR DESCRIPTION
**Pull request by halfzebra**
Hello @shuhei!

This is a pretty cool app! I've noticed that you've put quite a lot of effort into making it work on mobile really well. I have added the basic [Progressive Web App](https://developers.google.com/web/progressive-web-apps/) stuff so it works even better on Android.

With this PR it's possible to use it in offline and add it to the home screen as an "app".

This is how it looks on my Google Nexus:

21764276_1731872960218983_1876531043_o

Please feel free to kill this PR if it doesn't make sense.

### CODE REVIEW

**Comment by shuhei** [comment]
@halfzebra Wow, this is amazing. Thank you very much for your great work on create-elm-app and this PR!

**Comment by shuhei** [comment]
Currently this app is deployed to GitHub Pages with a custom domain, which does not support HTTPS. I'll find another option for deployment to enable service workers!

**Comment by halfzebra** [comment]
@shuhei happy to help!

My bad I've missed that you're not using HTTPS!

Please feel free to hit me if you need anything fixed in Create Elm App!

**Comment by shuhei** [comment]
@halfzebra Now it has HTTPS using Cloudflare :smile:

**Pull request merged**
